### PR TITLE
Price Table: Add Hover Text using Title Attribute

### PR DESCRIPTION
**Pull request by AlexGStapleton**
Related: https://github.com/siteorigin/siteorigin-premium/pull/385

### CODE REVIEW

**Comment by Misplon** [comment]
I ran this through the W3C Validator and didn't find any issues with the `title` tag being present when the title field is empty. Are we sure that's ok?

**Comment by AlexGStapleton** [comment]
I just had a quick look over the WCAG and don't see any mention of empty title tags causing issues. I did it this way to make that line more readable, but if you would prefer it's not output if it's empty, let me know.

**Comment by Misplon** [comment]
Ok cool, thanks for checking. This fine. If it gets raised then we can re-look at it.

**Comment by Misplon** [comment]
Or if Greg wants it removed if empty.

**Comment by gregpriday** [comment]
I'd personally have gone for leaving out the title tag if it's empty, but it is more readable like this and it doesn't make a huge difference.

**Comment by Misplon** [comment]
Got you. Thanks for the feedback.

**Pull request merged**
