### PR TITLE
Contact: Add Field max width setting

### PR DESCRIPTION
**Pull request by AlexGStapleton**
Resolve https://github.com/siteorigin/so-widgets-bundle/issues/988

### CODE REVIEW

**Comment by AlexGStapleton** [comment]
@Misplon How do you want to handle the datetime field? We could maybe exclude it or apply the width to its container instead.

**Comment by Misplon** [comment]
Is it perhaps possible to apply the max-width to the form container?

**Comment by Misplon** [comment]
Mmm, I wonder how we landed up with a label width setting? Is there a use case?

**Comment by Misplon** [comment]
Let's try adding the width to the date/time container.

**Comment by AlexGStapleton** [comment]
How does that look?

> Mmm, I wonder how we landed up with a label width setting? Is there a use case?

The setting was introduced [here](https://github.com/siteorigin/so-widgets-bundle/commit/ff3cbb964ec9fb837bb36b139475ec40e0c73a52). I suspect it was added to help with readability.

**Comment by Misplon** [comment]
Thanks, mate.

* Should we drop the max-width at the mobile resolution? I think we should.
* Should we apply the max-width to the map in the location field?

**Comment by AlexGStapleton** [comment]
The last commit disables the field width on mobile and applies the Field Max Width to the Location field container.

**Comment by AlexGStapleton** [comment]
@Misplon We don't have to introduce a breakpoint widget setting, but it is consistent with other widgets (Slider, Hero, Layout Slider, and Social Media Buttons), and allows for the breakpoint to be adjusted if Page Builder isn't being used.

**Comment by Misplon** [comment]
Ahh, true.

**Review by Misplon — APPROVED** [review]

**Review by gregpriday — APPROVED** [review]

**Pull request merged**
