### PR TITLE
Added right margin to color picker input

### PR DESCRIPTION
**Pull request by Misplon**
Resolves:

spacing

### CODE REVIEW

**Comment by AlexGStapleton** [comment]
This works, but it might be a better idea to apply the spacing directly to the Clear button. My reasoning for this is that the Default button already has spacing applied so if a Default button is present, it results in additional spacing when this change is present.

Before:


After:

**Comment by Misplon** [comment]
Good points. Please, now check style fixes for Clear and Select Content buttons. Select Content is the button for Destination URL. Thanks.

**Comment by Misplon** [comment]
Probably should have gone with another PR but thought we could squeeze it in here this time.

**Comment by Misplon** [comment]
Super, thanks.

**Pull request merged**
