### PR TITLE
Layout Slider: Prevent header color from affecting SiteOrigin Headline

### LINKED ISSUE #432: Layout Slider Overrides Headline color setting
The layout slider will override the SiteOrigin Headline widget's headline and sub-headline colors. Ideally, the layout slider should only be able to override things like the text widget and the editor widget and shouldn't be able to override the headline widget.

### PR DESCRIPTION
**Pull request by AlexGStapleton**
Resolves #432

### CODE REVIEW

**Comment by AlexGStapleton** [comment]
@Misplon Can you think of any other widgets with header color options that should be excluded?

**Comment by Misplon** [comment]
Not right now. Let's start with this and add further if there are additional reports.

**Comment by AlexGStapleton** [comment]
That's a decent idea.

Please note that change will ensure that the header colors remain for everything _but_ the SiteOrigin Headline widget - no other widget will be affected by this change.

**Comment by Misplon** [comment]
@AlexGStapleton Was there anything you needed to add here?

**Comment by AlexGStapleton** [comment]
Honestly, I'm not too sure. 😕

**Comment by braamgenis** [comment]
Yeah, so I was suggesting we should add an optional setting to prevent this for _all_ widgets and not just Headline, but now I'm thinking we should remove the setting altogether. My guess is this setting was meant for the Hero widget, which has a TinyMCE field as it's content editor. IMO it doesn't really make sense for the Layout Slider which could contain widgets with their own header color settings.

**Comment by AlexGStapleton** [comment]
The only potential issue I see with removing this setting is that certain users may already be relying on these settings. Is that something we're okay with? I know @Misplon is typically very against these sort of setting removals.

**Comment by braamgenis** [comment]
Yeah, usually I'm very against it too, but in this case I think leaving it will cause more unintented consequences down the line. You guys will have a better idea of how many users this might affect though, so if you and @Misplon think we should just stick to fixing it for Headline widget, I'm happy to merge as is.

**Comment by Misplon** [comment]
I'm cool with @braamgenis suggestion here (weighing up the greatest cost).

**Comment by braamgenis** [comment]
Yeah, I would say so. `heading_size` isn't even being used at all. Perhaps as a compromise, we can remove the form fields and keep using the settings if they exist for users who may have been relying on them,

**Comment by AlexGStapleton** [comment]
I can't figure out a way to dynamically filter out widget forms while still providing access to the forms to those that have already set them up. I know we've spoken about this previously Braam but, do you have any ideas?

**Comment by braamgenis** [comment]
@AlexGStapleton I'll have to dig around a bit for this one. Will take a proper look as soon as some other higher priority issues have been taken care of.

**Comment by AlexGStapleton** [comment]
That's fine and completely understandable.

**Comment by braamgenis** [comment]
Fixed in a066c334efef2449a8a812ff550cf944ebca8119

**Comment by Misplon** [comment]
Thanks brother, looking good.

**Pull request closed without merging**
