### PR TITLE
Testimonials: Standardize label prefixing and capitalisation

### PR DESCRIPTION
**Pull request by SmashBrando**
This fixes the issues referenced in this issue #677

### CODE REVIEW

**Comment by braamgenis** [comment]
@AlexGStapleton Please check the thread in #677 as there was further discussion around the proposed changes. If you want to resubmit a fresh PR would be ideal.

**Comment by AlexGStapleton** [comment]
@SmashBrando I've talked to Braam about this PR and his main reason for wanting a fresh PR was due to the required merge to update it and required changes If you're still keen, can you please resubmit this PR with the additional discussed in #677? It would be much appreciated but I completely understand if you're no longer keen and that's completely fine - thank you for your contribution!

**Comment by SmashBrando** [comment]
@AlexGStapleton I'll put this on my calendar to revisit next week.

**Comment by SmashBrando** [comment]
@AlexGStapleton sorry for the delay - I believe I conformed to the requested text label update on Radius.

**Comment by AlexGStapleton** [comment]
That looks good to me. While I mentioned Braam would prefer a new PR it looks like your last commit may have resolved any issues he may have had with it. @braamgenis Can you confirm if this is the case, or would you still like a new PR submitted?

**Comment by Misplon** [comment]
Thanks so much for the effort here. We really appreciate the support and involvement. I'm going to close in favor of https://github.com/siteorigin/so-widgets-bundle/pull/874. If any questions or feedback arise in the future, please let us know. Thanks again :)

**Pull request closed without merging**
