### PR TITLE
Beaver Builder: Update Font Awesome CSS

### LINKED ISSUE #825: Beaver Builder: SiteOrigin widgets aren't working
SiteOrigin widgets don't appear to be functioning in Beaver Builder. The only PHP error I can see is:

`Notice: Undefined index: style in /Users/andrew/Dropbox/Sites/siteorigin/wp-content/plugins/beaver-builder-lite-version/classes/class-fl-builder.php on line 2919`

For example, try testing the button widget, it doesn't appear to output after saving.

Font Awesome icons aren't showing in the admin:

icons

Originally reported on our forum [here](https://siteorigin.com/thread/widgets-not-working-5/).

I've tested with so-widgets-bundle.1.15.0-rc.3 and the issue persists.

### PR DESCRIPTION
**Pull request by AlexGStapleton**
Resolves #825

### CODE REVIEW

**Comment by gregpriday** [comment]
Looks good!

**Comment by braamgenis** [comment]
It seemed like @Misplon wanted this and the other Beaver Builder fix to go out quite urgently, so I mentioned to him in [slack](https://siteorigin.slack.com/archives/C02SYBBH2/p1549647445001100), that I would merge this into the release branch so that it goes out with the pending release. I should be able to cherry pick this out of the develop branch.

**Comment by Misplon** [comment]
That would be great. Without this fix, large parts of the WB are broken in Beaver, I think that's well worth resolving as soon as we're able to.

**Comment by gregpriday** [comment]
Aaah, epic. Yeah, let's move to keeping as much of the issue/code related comms in Github as possible. Much harder to keep track of slack.

**Pull request merged**
