### PR TITLE
Release 1.15.3

### PR DESCRIPTION
**Pull request by braamgenis**
* Image grid: Fallback support, alt text, use measurement fields.
* Features: Fix responsive layout.
* Google Maps: Update to use gesture handling and separate zoom level for mobile.
* Google Maps: Default height when height field is empty.
* Sliders: Option to always show navigation on mobile devices.
* Accordion: Keyboard navigation.
* Beaver Builder: Fix icons and widgets not saving.
* Video: Allow using YouTube embed URLs.
* Post Carousel: Accessibility improvements.
* Escape namespaced widgets in previews.
* Flag additional metaboxes as incompatible with the block editor.
* Fix state emitters for sub-widget fields.
* Google Maps: Remove API key field from widget form, in favor of global API key field.
* Google Maps: Display notice when API key missing.
* Contact form: Prevent double nonce.
* TinyMCE field: Prevent twemoji from replacing emoji in the textarea.
* Widget block: Show appropriate message when widget is missing or deactivated.
* Accordion: Fix open/close icon layout when set to left position.
* Social Media Buttons: Prevent the phone network from opening in a new window.
* Google Maps: Add map styles filter.
* Image radio field: New field created.
* Posts field: Option to specify allowed post types.
* Contact form: Add description to reCAPTCHA field specifying reCAPTCHA v2.

### CODE REVIEW

**Comment by Misplon** [comment]
@braamgenis Please, could you update the Google Maps gesture docs link to the Google page as discussed in #841. Thanks :)

**Comment by braamgenis** [comment]
@Misplon Where do you want the link to point? In the above comment you say it should link to the Google page, but in #841 [here](https://github.com/siteorigin/so-widgets-bundle/issues/841#issuecomment-468746521) you suggest linking to siteorigin.com docs.

**Comment by Misplon** [comment]
Sorry for confusion I agree with you and original plan to link to Google
page and anchor.

**Comment by braamgenis** [comment]
@gregpriday Mind checking those last few commits?

**Pull request closed without merging**
