### PR TITLE
Post Carousel: Add default thumbnail

### PR DESCRIPTION
**Pull request by AlexGStapleton**
When a post doesn't have a featured image set, it shows nothing. This PR will allow users to specify a default image to provide more of a site-specific touch to their carousel.

### CODE REVIEW

**Comment by braamgenis** [comment]
@AlexGStapleton I've made the previously mentioned changes, but don't seem to be able to push to your fork. Have you [enabled permission](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) for repo maintainers on this PR?

**Comment by AlexGStapleton** [comment]
Oh awesome. Uh, oddly, I have.



Maybe just submit a new PR? I don't really care if any (if there is any) of the code is attributed to me.

**Comment by braamgenis** [comment]
Oh, hmm... I must just be doing it wrong. :confused: I'll submit a new PR with your code merged in so your commits are still under your name. It's not just about attribution, but also who to blame if things break. :stuck_out_tongue_winking_eye:

**Comment by braamgenis** [comment]
Closing in favour of #412

**Comment by AlexGStapleton** [comment]
It's okay mate, you can take the blame mate. ;)

**Pull request closed without merging**
