### PR TITLE
Posts Selector Relative Dates

### LINKED ISSUE #466: Post Selector: Ability to specify current day, month, year.
A semi-common request for the additional field is the ability to set relevant current dates, for example, day, month, year, etc. An example use case would be if I wanted to include all posts I posted last week in a post loop I would currently have to manually update the date range every week.

[Slack reference](https://siteorigin.slack.com/archives/C02SYBBH2/p1493732957835081)

### PR DESCRIPTION
**Pull request by braamgenis**
To resolve #466. Allow selection of a date range relative to today.

### CODE REVIEW

**Comment by AlexGStapleton** [comment]
0 as the to date seems to be ignored. For example, if I set the dates from 1 days ago to 0 days ago, nothing will be returned. 

This may be related but, it also seems like if it's a single day different, nothing will be returned. For example, from 3 to 4 days.

**Comment by braamgenis** [comment]
@AlexGStapleton The default for date queries excludes the selected dates. I.e. if you select from 1 May to 3 May it will only return the posts for 2 May. I've set it to always include the selected dates as that feels more intuitive to me. Please take a look and let me know what you think.

**Comment by AlexGStapleton** [comment]
Much better! 👍

**Comment by gregpriday** [comment]
Everything looks good on the code side, so going to merge.

**Pull request merged**
