### PR TITLE
Widgets Page: Add Spacing to Preview BTN

### PR DESCRIPTION
**Pull request by AlexGStapleton**
Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1472
A build (or `build:dev`) will be required to view this change.

### CODE REVIEW

**Comment by Misplon** [comment]
Thanks, mate. It's specifically the spacing between the Preview button and the Delete and Done links I'm looking to make the same as Page Builder.

Widgets_‹_SiteOrigin_—_WordPress

**Comment by AlexGStapleton** [comment]
Ah. Those two items aren't present at the bottom of widgets in Widgets so I had thought you were referring to the preview button. Can you please provide me with a screenshot of the specific area you would like to replicate the spacing of?

**Comment by Misplon** [comment]
For sure. Please, find below. Thanks, mate.

Edit_Page_“Page_Builder”_‹_SiteOrigin_—_WordPress_🔊

**Comment by Misplon** [comment]
Thanks, mate. Did you mean to use margin-bottom?

**Comment by Misplon** [comment]
Here is what I'm seeing:

Screenshot_2022-04-11_at_16_14_40

Let's close this PR. The issue is there is no Help link. I'll add that in a separate PR.

**Pull request closed without merging**
