### PR TITLE
Blog: Add Excerpt Length

### PR DESCRIPTION
**Pull request by AlexGStapleton**
Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1576

Please test with and without excerpt length adjustment. Please also confirm `siteorigin_widgets_blog_excerpt_length` still works as intended. Test snippet:

```
add_filter( 'siteorigin_widgets_blog_excerpt_length', function( $length ) {
  return 10;
} );
```

### CODE REVIEW

**Comment by Misplon** [comment]
Thanks, mate.

- If you set a count over 55, is it working?
- Let's make the setting conditional on selecting Excerpt but not on enabling excerpt read more.
- I'm keen to make the excerpt dots the same as Corp ... vs. the default of [...]

**Comment by Misplon** [comment]
Super; thanks. When you have a moment, can you perhaps check out the fatal in template/base.php. Cheers!

**Comment by Misplon** [comment]
Thanks, mate. I'm seeing settings remain when switching to Portfolio. Is that happening for you or just a M1 issue?

https://user-images.githubusercontent.com/789159/184901149-413022f8-c526-45c4-aa81-37a0c86fb596.mov

**Comment by AlexGStapleton** [comment]
Ah. That's an oversight. Due to multi-conditional state emitters not currently being possible (https://github.com/siteorigin/so-widgets-bundle/issues/1254), we have to choose whether we want to show Excerpt Length when Post Content is set to Excerpt or when a template that supports excerpts is enabled.

I suspect the latter will be your preference but I'll wait for your reply before making any changes.

**Comment by Misplon** [comment]
We can't do both? Both would be ideal.

**Comment by Misplon** [comment]
If Excerpt Length is displayed when Post Content is set to Excerpt would Excerpt Length be hidden for Portfolio as there isn't a Post Content setting in the Portfolio template.

**Comment by AlexGStapleton** [comment]
> We can't do both?

We cannot. https://github.com/siteorigin/so-widgets-bundle/issues/1254 would be required for that - it's quite a large change to make just for this.

> If Excerpt Length is displayed when Post Content is set to Excerpt would Excerpt Length be hidden for Portfolio as there isn't a Post Content setting in the Portfolio template.

Hm. By default, no (that's just conditionals, which aren't supported), however, if I juggle a few things around with preset data I can do this. Okay. Done. The last PR accounts for this.

**Review by Misplon — APPROVED** [review]

**Pull request merged**
