### PR TITLE
Widgets Page: Prevent Menu Search Overlap on Mobile

### PR DESCRIPTION
**Pull request by AlexGStapleton**
Before:
Screenshot_2021-05-03 SiteOrigin Widgets ‹ SiteOrigin — WordPress

After:
Screenshot_2021-05-03 SiteOrigin Widgets ‹ SiteOrigin — WordPress(1)

### CODE REVIEW

**Comment by AlexGStapleton** [comment]
@Misplon What are your thoughts on reducing the page title and/or verticaly aligning the icon with the title?

**Comment by Misplon** [comment]
Sounds good, thanks.

**Comment by Misplon** [comment]
Let's look at left aligning the search field, thanks mate.

wb

**Comment by AlexGStapleton** [comment]
How does that look?

**Review by Misplon — APPROVED** [review]

**Pull request merged**
