### PR TITLE
5.8 Widgets Changes

### PR DESCRIPTION
**Pull request by AlexGStapleton**
This PR contains changes required for WB to be compatible with the new widgets interface.

### CODE REVIEW

**Comment by AlexGStapleton** [comment]
A bunch of field styling changes are required.

Screenshot 2021-06-12 at 01-54-11 Widgets ‹ blueprint — WordPress

**Comment by Misplon** [comment]
@AlexGStapleton Are you seeing the following issues?

**Widget Block:**

Select field:
select

**Button Widget:**

Widgets_‹_Puro_—_WordPress

**Comment by Misplon** [comment]
Ahh, I didn't have Page Builder also on the 5.8 branch, my bad.

**Comment by Misplon** [comment]
@AlexGStapleton If you can replicate the above then I think let's start by resolving the Widgets Block select field issue. Also, note that there is a jump down and up in the block header when adding a widget. Not sure if that's on us. Once the Widgets Block is sorted, please, can you run through the Button widget to start with and align it with the Button widget styling in traditional PB as much as is possible?

**Comment by AlexGStapleton** [comment]
I'm able to replicate the widget select alignment - that's fixed by the last commit. I wasn't able to replicate the pictured issues in your other screenshots. Did you make a build?

Here's a screenshot of what I see:

Screenshot 2021-07-03 at 06-56-15 Edit Page ‹ blueprint — WordPress

I do however see issues with the selects. That'll be fixed in the next commit.
Screenshot 2021-07-03 at 06-57-12 Edit Page ‹ blueprint — WordPress

**Comment by Misplon** [comment]
Thanks, I did create a build. My Button Widget screenshots are from a Button Widget. Try inserting a Button Widget, not a Button via the Widgets Block. Cheers, mate.

**Comment by AlexGStapleton** [comment]
Ah, my mistake. Looks like something changed in WP that broke all of the CSS changes I made for WB and PB. 😞

**Comment by Misplon** [comment]
Bleak! When is the release date? Should we wait?

**Comment by AlexGStapleton** [comment]
Okay, great, worked it out. They've added a bunch of legacy widget CSS styling and prefixed it using a selector that's even more specific than the WB one. Just need to be more specific with _everything_ than that and we're good to go.

> When is the release date?

July 20th. Plenty of time.

> Should we wait?

No.

**Comment by AlexGStapleton** [comment]
That last commit should resolve most, if not all of the issues in the WB fields. Please give it a try and let me know if you find any oddities. I'll hit the PB PR tonight.

**Comment by Misplon** [comment]
Thanks, mate. The Widgets Block issue is resolved. Please, can you check the standalone Button Widget and confirm those issues are resolved? They don't seem to be for me.

**Comment by AlexGStapleton** [comment]
I'm getting the same results after adding a SiteOrigin Button Block.

I should note that there isn't actually a standalone widget anymore. When you search for one of the WB widgets (or really, any widget) a "shortcut" will appear and upon selecting it a Legacy Widget Block will be added with the selected widget enabled. Adding a Legacy Widget and then selecting the widget will result in the same thing.

--

The last commit will resolve Repeater Styling (due to https://github.com/siteorigin/so-widgets-bundle/pull/1332/commits/89454bb30a03904360558608fb31e50a7aa0d481 the repeaters would have zero styling).

**Comment by AlexGStapleton** [comment]
The last commit restores general styling for links. The easiest place to test this is the Post Loop widget which has a link just after the last field.

**Review by Misplon — APPROVED** [review]

**Review by gregpriday — APPROVED** [review]

**Pull request merged**
