### PR TITLE
Added Yandex.Zen to Social Media Buttons widget

### PR DESCRIPTION
**Pull request by sabinich**
add yandex.zen as new network

### CODE REVIEW

**Comment by braamgenis** [comment]
I'm afraid the Yandex Zen icon is not available in the icon pack we use for these networks: 
https://fontawesome.com/icons?d=gallery&q=yandex

**Comment by gregpriday** [comment]
I see `yandex` is in Font Awesome now. Is this different from `yandex-zen`?

If it is different and we can't use `yandex`, then let's close this PR until it's available.

**Comment by braamgenis** [comment]
@gregpriday Yeah, I think Yandex is the company and Yandex Zen is the social network and they have different icons. Closing for now.

**Comment by sabinich** [comment]
i created feature request for adding new icon to awesome font https://github.com/FortAwesome/Font-Awesome/issues/14525 about month ago.. ;-\

**Comment by AlexGStapleton** [comment]
When a Yandex icon is added to Font Awesome, we'll re-open this and look at merging it.

**Comment by map788** [comment]
After 2022 Zen not more yandex - new icon
https://download.cdn.yandex.net/from/yandex.ru/support/ru/zen/files/zen-new-icon.eps

**Pull request closed without merging**
