### PR TITLE
Post Carousel: Ensure Dots Can Appear When Arrows Are Disabled

### PR DESCRIPTION
**Pull request by AlexGStapleton**
This PR will ensure the Post Carousel is able to show the dots navigation when arrows are disabled.

### CODE REVIEW

**Comment by Misplon** [comment]
@AlexGStapleton, I've tested with a build. The Overlay dots don't seem to be displayed with the arrows removed.

[page-builder.json.zip](https://github.com/siteorigin/so-widgets-bundle/files/9640217/page-builder.json.zip)

**Comment by Misplon** [comment]
@AlexGStapleton For some reason, this PR is working for me now.

I'm noticing a dots alignment difference in the following two situations:

1. Disable arrows globally. Dots stay left aligned.
2. Disable arrows for Desktop, but leave enabled globally; dots are right aligned.

Assuming you can recreate the issue, do you want to tackle this in another PR?

**Comment by AlexGStapleton** [comment]
> I've tested with a build. The Overlay dots don't seem to be displayed with the arrows removed.

[I created a test build](https://drive.google.com/uc?id=1w8mbW2aKafzzHU6PYcDYW80khbRa7tWR) of this PR and the layout you provided, I get:



Post Carousel settings are set to default. I've uploaded this build to the demo site and [I'm able to replicate this result ](https://demo.siteorigin.com/corp/sandbox-2/)(and the below results). I've modified the provided layout ([downloadable here](https://drive.google.com/uc?id=1n1Hf2d7TxZHjQtrwPm0Z1mcbk1CP7iTX)) and here are the results (and the setting values) I get:



(navigation is due to screenshot capture)

> Disable arrows globally. Dots stay left aligned.

Would you like to centre align or right align the dots?

> Disable arrows for Desktop, but leave enabled globally; dots are right aligned.
I can't replicate this either (see second screenshot). When testing this PR, did create the Post Carousel before or after switching to this PR? If it's before, did you make a setting change? I ask as it's possible widget CSS is present.

**Comment by Misplon** [comment]
@AlexGStapleton On a separate issue, did you adjust your carousel colors? The issue of the incorrect defaults being loaded or no defaults being loaded is present in the grey background and red text of the post meta in your screenshots.

**Comment by AlexGStapleton** [comment]
The Post Carousel widgets seen in my screenshots are duplicates of the Post Carousel in the layout you provided. If I create a New Post Carousel widget it looks as expected.

**Comment by Misplon** [comment]
Thanks. Perhaps a M1 presets type of issue then.

**Comment by Misplon** [comment]
Looks good now; unsure what the issue was when I was testing. Happy to move on.

**Review by Misplon — APPROVED** [review]

**Pull request merged**
