### PR TITLE
Social Media Buttons: Add Tiktok

### PR DESCRIPTION
**Pull request by AlexGStapleton**
Require https://github.com/siteorigin/so-widgets-bundle/pull/1093

### CODE REVIEW

**Comment by Misplon** [comment]
Thanks.

Are you sure you want the network so high up? I'd be ok with placing it alphabetically.

**Comment by AlexGStapleton** [comment]
I don't mind. I put it there because of the comment here.

https://github.com/siteorigin/so-widgets-bundle/blob/831ceaf61ee84ef330aa8fc8d47f7972263cc884/widgets/social-media-buttons/data/networks.php#L101

Going to re-order them now.

**Comment by gregpriday** [comment]
The original ordering was to put the most common networks first, and the rest in alphabetical order. Lets keep the more popular networks first, and just put TikTok in the alphabetical list. We can also move Google Plus down into the alphabetical list, since that's dead.

**Comment by gregpriday** [comment]
Actually, we should reassess that entire "most popular" list at some point. For this PR though, just move TikTok into the alphabetical list and keep the popular list unchanged.

**Comment by Misplon** [comment]
@gregpriday Super, that's what I was asking for. Thanks.

**Pull request merged**
