### PR TITLE
TinyMCE: Only Alter textarea id when field is added in repeater.

### PR DESCRIPTION
**Pull request by AlexGStapleton**
This PR resolves an error that results in TinyMCE sometimes not working correctly. An example of this is with the Editor or Tabs widget.

Follow up to https://github.com/siteorigin/so-widgets-bundle/pull/1146

### CODE REVIEW

**Comment by Misplon** [comment]
@AlexGStapleton Can you confirm this is working for you in the Tabs widget? I'm still seeing the issue.

**Comment by AlexGStapleton** [comment]
I can confirm this is working for me when using the Tabs widget. Please note that this PR modifies a core page builder script so `build:dev` must be run.

**Comment by Misplon** [comment]
I'm now running the Page Builder build task and have this branch, tinymce-error-fix, checked out for the Widgets Bundle. Page Builder is using develop. The issue persists. Can you send me a build?

**Comment by AlexGStapleton** [comment]
Disregard my last comment about using `dev:build` in PB - this clearly isn't a PB PR. 🤦‍♂️ 

Here's a build: [so-widgets-bundle.tinymce-fix.zip](https://github.com/siteorigin/so-widgets-bundle/files/5286802/so-widgets-bundle.tinymce-fix.zip)

I tried this build prior to sending it and it's working as expected for me.

**Comment by Misplon** [comment]
Thanks. The issue is persisting with this build. Perhaps try Chrome? I've also uploaded it to demo.siteorigin.com for testing.

https://demo.siteorigin.com/premium/wp-admin/post.php?post=4&action=edit

Try switching to the Text tab in the Visual Editor of a Tabs widget panel.

**Comment by AlexGStapleton** [comment]
Ah. I wasn't aware that error occurred for you when you changed mode. The initial commit was to resolve an issue with TinyMCE potentially not displaying when a widget is opened. The last commit changes the id as late as possible to resolve the error that occurs when changing mode in a repeater.

**Comment by AlexGStapleton** [comment]
The last commit resolves the duplication issue for existing widgets. It doesn't help for new widgets - the duplicated item text mode won't display correctly.

**Comment by Misplon** [comment]
Looking good on my end. Anything else that needs to be added?

**Comment by AlexGStapleton** [comment]
How does that look? Please note that if you're using an older PR branch you you may get this error https://github.com/siteorigin/siteorigin-panels/pull/809 which will prevent the text toolbar from appearing. That happens without or without the changes in this PR or https://github.com/siteorigin/so-widgets-bundle/pull/1146.

**Review by Misplon — APPROVED** [review]

**Review by gregpriday — APPROVED** [review]

**Pull request merged**
