### PR TITLE
Removed static height declaration

### PR DESCRIPTION
**Pull request by Misplon**
Resolves https://github.com/siteorigin/so-widgets-bundle/issues/926.

@AlexGStapleton Can you see an issue with doing this?

### CODE REVIEW

**Comment by AlexGStapleton** [comment]
I don't see any direct issues with doing this, but I'm not familiar why a height was specified in the first place so there may be something I'm oving looking.

To play it safe, it might be better to change `height` to `min-height` rather than removing the height altogether. That's what's currently done for the drop-down in the measurement field.

**Comment by Misplon** [comment]
Sounds good. Added `min-height`.

**Comment by AlexGStapleton** [comment]
Looks good! 👍

**Comment by Misplon** [comment]
Thanks!

@gregpriday quick check when ready.

**Pull request merged**
