### PR TITLE
"Pre-fill" hero if height is set

### LINKED ISSUE #937: Hero: If Height set, add height to Hero widget container to prevent "jump"
The Hero widget doesn't have a proper sentinel as it's instead applied to a container within the slider itself which isn't visible until after the DOM has loaded. This can result in the Hero widget "jumping" into view. This can be avoided by applying the Height, if set, to a container outside of the slider but still within the regular widget container.

### PR DESCRIPTION
**Pull request by AlexGStapleton**
Resolve #937

### CODE REVIEW

**Comment by Misplon** [comment]
Looks good. Should we add another rule if a responsive height is set?

**Comment by AlexGStapleton** [comment]
We can. I thought about doing that but honestly, I have never come across any reports of this ever being an issue on mobile.

**Comment by Misplon** [comment]
Yeah, let's take care of this for mobile too while we are here.

**Comment by Misplon** [comment]
@gregpriday Functionality is good, just a quick code review, please. Thanks mate.

**Pull request merged**
