### PR TITLE
Contact: Allow whitelisted HTML in Checkboxes options

### PR DESCRIPTION
**Pull request by AlexGStapleton**
This PR will allow users to add HTML to checkboxes options. A use case for this is for GDPR type validations ("here's a link to our privacy policy").

### CODE REVIEW

**Comment by Misplon** [comment]
Spaces surrounding an `a` tag appear to be stripped, is that happening for you?

**Comment by AlexGStapleton** [comment]
Ah. That's happening due to applying flex to the checkbox label. Do you have any issues with removing the `display: flex` from the checkbox label and removing the `float` from the checkbox?

**Comment by Misplon** [comment]
That doesn't result in the same alignment as before for me.

How about something like this. The following is for testing:

```
.sow-form-field-checkboxes label *:not(input) {
	display: contents;
}
```

**Comment by AlexGStapleton** [comment]
There are accessibility concerns with `display: contents` that have only _just_ been addressed in Chrome and haven't been addressed in Safari.

https://hiddedevries.nl/en/blog/2018-04-21-more-accessible-markup-with-display-contents

What are your thoughts on moving the input outside of the label, and connecting it to the label using a `for` attribute. it's not as simple, but it'll avoid this without potentially introducing other issues and it should look the same.

**Comment by Misplon** [comment]
Let's do that. We can apply flex to the list item.

**Comment by AlexGStapleton** [comment]
How does that look?

**Comment by Misplon** [comment]
@AlexGStapleton Can you confirm this is working for you? It isn't for me. Here is a live demo of this branch https://demo.siteorigin.com/corp/contact/.

**Comment by AlexGStapleton** [comment]
The widget on that page had the outdated widget LESS - you can tell by inspecting the checkbox label as it no longer has `display: flex;` applied and it doesn't have the same selector as the radio field.



I've made a design setting change to the contact form on that page (I changed the error notice background) and saved the page and it's now working as expected. This won't be required for normal users as widget CSS is regenerated after a plugin update.

**Comment by Misplon** [comment]
Thanks. I did do a plugin update though. It was a manual update but I bumped the version number.

**Comment by AlexGStapleton** [comment]
That's not the same as an automatic update. Having to manually update the widget to trigger a widget CSS refresh, or manually clearing the `siteorigin-widgets` CSS cache is expected during development, and not required during a proper release.

**Comment by Misplon** [comment]
Got you.

**Review by Misplon — APPROVED** [review]

**Review by gregpriday — APPROVED** [review]

**Pull request merged**
