### PR TITLE
Video Player: Allow External Videos to Loop

### PR DESCRIPTION
**Pull request by AlexGStapleton**
Requires https://github.com/siteorigin/so-widgets-bundle/pull/1298

Prior to this PR, the Loop setting would disappear if an External Video was selected.

### CODE REVIEW

**Comment by Misplon** [comment]
@AlexGStapleton Under which conditions can I get a YT video to autoplay and loop?

**Comment by AlexGStapleton** [comment]
@Misplon Tick Autoplay and Loop. As mentioned over Slack, certain browser features will prevent the autoplay. We can enforce this by setting the video muted by default - do you want to do that?

**Comment by Misplon** [comment]
Without mute being added if I'm not seeing autoplay in Chrome macOS, where is it happening?

**Comment by AlexGStapleton** [comment]
It's autoplaying without issue for me in Chrome and Firefox.

Are you okay with Mute being added as an optional setting? The description could be:
> Depending upon browser permissions, the video may not autoplay unless the video is also muted. For example, all mobile browsers require the video to be muted.

This makes it clear that if the user wants it to always autoplay they'll need to mute it.

**Comment by Misplon** [comment]
@AlexGStapleton Thanks, mate, I'll get back to you regarding the above.

I've taken this branch, merged develop, and created a build. Autoplay is working for me here https://demo.siteorigin.com/corp/video-test/ but looping isn't. Is looping working for you on that test page?

**Comment by AlexGStapleton** [comment]
Oh! The Video Widget template changes weren't merged, sorry about that. 🤦 
Please try again.

**Review by Misplon — APPROVED** [review]

**Review by gregpriday — APPROVED** [review]

**Pull request merged**
