### PR TITLE
Updated TinyMCE field to use new Editor JS API

### LINKED ISSUE #505: Elementor: When SiteOrigin Widgets Bundle is active, Editor.css isn't able to load can causes display issue with text widget
When SiteOrigin Widgets Bundle is active, wp-includes/css/editor.css isn't able to load can causes display issue with text widget

(left is when SiteOrigin Widgets Bundle is disabled and right is when it's enabled)

This may be related to #477

### PR DESCRIPTION
**Pull request by braamgenis**
Backwards compatible with <= WP 4.7. Still have a bit of testing to run through, but everything should be working as before. This should resolve #505, #477, and possibly other issues related to TinyMCE conflicts.

### CODE REVIEW

**Comment by AlexGStapleton** [comment]
Can confirm #477 is resolved by this.

**Comment by AlexGStapleton** [comment]
Editor is typically really small when it's first added to page. Normal size once saved.
	https://i.imgur.com/MxPNZZ4.png

**Comment by AlexGStapleton** [comment]
SiteOrigin Page Builder: After you add (and remove) a gallery widget, you'll be unable to interact with the editor until you change mode. This only happens if no other text is present

https://drive.google.com/a/siteorigin.com/uc?id=0BymU-6VMHHPfM19qZXFXY2NSX28
(you may not be able to see it, but just know that madly clicking ;)

**Comment by AlexGStapleton** [comment]
Beaver Builder: Text tab buttons missing

**Comment by AlexGStapleton** [comment]
Beaver Builder and VC
oEmbed doesn't work. This also occurred in 1.9.3 so it may be better to log this as a separate issue.

TinyMCE Advanced doesn't work - works without issue in 1.9.3.

**Comment by AlexGStapleton** [comment]
Visual Composer: Error when adding media to Editor for third party widgets. Images are added (and can be seen in in text mode) but it'll break the visual mode until reloaded. The error will occur with SiteOrigin Hero widget but the visual mode won't be broken by the error.

```
tinymce.min.js?ver=4603-20170530:15 Uncaught TypeError: a.replace is not a function
    at h (tinymce.min.js?ver=4603-20170530:15)
    at Object.getFontFamily (tinymce.min.js?ver=4603-20170530:3)
    at o.<anonymous> (tinymce.min.js?ver=4603-20170530:15)
    at b.e [as fire] (tinymce.min.js?ver=4603-20170530:10)
    at o.fire (tinymce.min.js?ver=4603-20170530:10)
    at Object.nodeChanged (tinymce.min.js?ver=4603-20170530:12)
    at o.nodeChanged (tinymce.min.js?ver=4603-20170530:13)
    at o.<anonymous> (tinymce.min.js?ver=4603-20170530:8)
    at b.e [as fire] (tinymce.min.js?ver=4603-20170530:10)
    at o.fire (tinymce.min.js?ver=4603-20170530:10)
    at Object.add (tinymce.min.js?ver=4603-20170530:8)
    at e (tinymce.min.js?ver=4603-20170530:8)
    at o.<anonymous> (tinymce.min.js?ver=4603-20170530:8)
    at b.e [as fire] (tinymce.min.js?ver=4603-20170530:10)
    at o.fire (tinymce.min.js?ver=4603-20170530:10)
    at Object.p [as execCommand] (tinymce.min.js?ver=4603-20170530:9)
    at o.execCommand (tinymce.min.js?ver=4603-20170530:13)
    at Object.send_to_editor (media-upload.js?ver=4.8:23)
    at Object.insert (media-editor.js?ver=4.8:775)
    at origEditorSendAttachmentCallback (frontend-editor.min.js?ver=5.2:1)
    at Object.<anonymous> (frontend-editor.min.js?ver=5.2:1)
    at i (jquery.js?ver=1.12.4:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4:2)
    at Object.<anonymous> (wp-util.js?ver=4.8:106)
    at i (jquery.js?ver=1.12.4:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4:2)
    at y (jquery.js?ver=1.12.4:4)
    at XMLHttpRequest.c (jquery.js?ver=1.12.4:4)
```

**Comment by braamgenis** [comment]
@AlexGStapleton The image gallery issue exists in the main WP editor too, with all plugins disabled. There seems to be some invisible HTML left behind when removing the gallery. It can be deleted by simply pressing backspace after removing the gallery.

**Comment by braamgenis** [comment]
As discussed in Slack, the BB issue seems to have been a once-off as neither of us can reproduce again.

**Comment by braamgenis** [comment]
@AlexGStapleton What do you mean by oEmbed not working? Do you mean that it's not converting the link to a video in the editor itself? If so, I think we can live with that for now as long as the video shows up in the front end.

**Comment by AlexGStapleton** [comment]
Correct. It doesn't convert the URL in the editor, and sadly, it doesn't convert it on the front end either. 😢

**Pull request merged**
