### PR TITLE
Add max number of items for repeater field

### PR DESCRIPTION
**Pull request by xella29**
Hello, I reopen this issue, with modifications you asked ! 
Hope it will be good this time, I think this update is quite useful for users ! :)

### CODE REVIEW

**Comment by Misplon** [comment]
Hi xella29

Thanks for your PR. 

Before Greg can review, the PR should only contain changes relevant to the issue you're fixing. Please, take a quick look at the changes in [admin.js](https://github.com/siteorigin/so-widgets-bundle/pull/917/files). There are many changes to that file that aren't relevant to the PR. Although those changes might be correct they muddy the commit as they aren't relevant to the issue you're solving and therefore make it harder to review. I've tried to resolve this issue for you but have run into a problem with my Git app (Tower) not always seeing the fixes I'm making. If you update your PR so that the changes are only those necessary, I'll ask Greg to review. 

Thanks :)

**Comment by Misplon** [comment]
One way forward would be to revert my second commit https://github.com/xella29/so-widgets-bundle/commit/2417115966ea65a33d737cac49e12246d1b8cd18 and revert your commit to `admin.js` https://github.com/xella29/so-widgets-bundle/commit/604e816814fd489cd62a27ed0025f35d38375557 and then recommit the admin.js changes with only the necessary lines changed. The PR should then be ready for review.

**Comment by xella29** [comment]
Hello, Sorry but I don't understund what you are expecting from me ? I did a git pull on the projet, so I get your update, but I have nothing more to commit because my change are included also in your latest commits. You can see my changes in the commits I did. Its concerns the two file "admin.js" from the base folder, and the repeater class file (from base > inc > fields >repeater.class.php).

**Comment by Misplon** [comment]
Hi. Most likely your Text Editor altered formatting. Can you see in the screenshot below, those are changes but not related to what you're changing.

Add_max_number_of_items_for_repeater_field_by_xella29_·_Pull_Request__917_·_siteorigin_so-widgets-bundle

**Comment by xella29** [comment]
Oh ! Ok, I understand. How can we do ? From wich file I can go back to add my update ?

**Comment by Misplon** [comment]
The fix I tried to make, manually resolving each issue, that wasn't the correct path to take.

As far as I can see, the way forward would be to revert my second commit https://github.com/xella29/so-widgets-bundle/commit/2417115966ea65a33d737cac49e12246d1b8cd18 and also revert your commit where you edit `admin.js`. https://github.com/xella29/so-widgets-bundle/commit/604e816814fd489cd62a27ed0025f35d38375557. Then you can redo the `admin.js` commit but ideally, this time, only with the exact lines changed that need to be changed.

**Comment by xella29** [comment]
I try to take the current repository admin.js file, and add my change. I commit this change, is it okay for you ?

**Comment by Misplon** [comment]
Almost there, just check the last line: https://github.com/siteorigin/so-widgets-bundle/pull/917/files. There is a change showing there, it's because the original file had a new line at the end of file which has been removed in the PR. If you add the new line back then that change will be removed.

**Comment by xella29** [comment]
And now is it okay ?

**Comment by xella29** [comment]
And now, is it okay ?

**Comment by Misplon** [comment]
Now it's ok with only the necessary changes making it easier to read. Greg can now review the PR and advise further from there. Thanks.

**Comment by xella29** [comment]
Ok, thank you for the support ! Sorry for the difficulties, this is my first contribution to a project !

**Comment by Misplon** [comment]
Sure, no problem :) Greg will take a look at the PR when he's able and advise from there. Thanks.

**Comment by Misplon** [comment]
Hi Axelle

I hope your week is off to a good start.

I had a chance to go over the front-end of your PR over the weekend. Please, find two points below that I think would help improve the overall functionality of this change.

**Closing the last border**
When the last repeater is used, I think it might improve the design if there was a bottom border to match the border around the repeater. 

Edit_Page_‹_SiteOrigin_—_WordPress

**Duplicate icon**
At the moment, the duplicate icon is removed at the max. I think we should consider leaving the icon in place. We could perhaps change the icon opacity to `0.5` and set the cursor to `not-allowed`.

Screenshot 2020-01-13 at 14 36 27

Let me know your thoughts, thanks :)

**Comment by Misplon** [comment]
Hi Axelle

Thanks again for your contribution. I'm going to close this PR for the time being. If you'd ever like to revisit and take a look at the few outstanding items, please, let us know. 

Cheers for now.

**Pull request closed without merging**
